version: '3.9'

services:
  postgres:
    image: ${POSTGRES_IMAGE}
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PORT: ${DB_PORT}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: ${REDIS_IMAGE}
    container_name: redis
    restart: unless-stopped
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
      args:
        NODE_IMAGE: ${NODE_IMAGE}
    container_name: api
    restart: unless-stopped
    env_file:
      - .env
    environment:
      DB_HOST: postgres
    depends_on:
      - postgres
      - redis
    volumes:
      - ./api:/usr/src/app
      - api_node_modules:/usr/src/app/node_modules
    command: npm run start:dev
    ports:
      - "${API_PORT}:${API_CONTAINER_PORT}"

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
      args:
      # reuse same base node image from .env
        NODE_IMAGE: ${NODE_IMAGE}
    container_name: web
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - api
    environment:
      # Frontend talks to backend via Docker service name "api"
      VITE_API_URL: "http://api:${API_CONTAINER_PORT}"
    volumes:
      - ./web:/usr/src/app
      - web_node_modules:/usr/src/app/node_modules
    ports:
      - "${WEB_PORT}:${WEB_CONTAINER_PORT}"

volumes:
  postgres-data:
  api_node_modules:
  web_node_modules: